language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Q/GmgzKmgV6KelU4VNucLZS5mJYISPlTsSWoqQNxBURQvSLqUNVK34fI5QVjnqydQbGlkcFQyVzQ8z+BU9YH5MOpbVsckIo7yYtm+/LjmPCi5dqNk4j9h+Kep87qZoDhdQQonCHP1d/RVRiE5Fvc5bQnqsM6INe9J4VK0JstNyH8eGgvGQnqgC0mvcAcl9MRc8ZRQMC6oWp2ki6Gu3SNrkP42aGghDzCUT0SG9sbGxSrwnPPVlcm9j4xlVEbyXYJ5io0PLyJjvVfvM4B0DDpjZgx50+SK16xsXlnGKCl84Js6pNgDwPv47SXRmjemdQv4/Rtt6xKFgGmZVnvybMfYMr2OoVHvrtw5p0OH+XJ6U3b6qYP4fIt79GSo2ocnX2LjjaSS0JKW8DNdJKTJtfQ7kg+Ru/PZSNNGeoma4D63WxczRB4ft/OI7GauOrklFYnY/hqijx2V9Za8qLou0Cppqao8bRbBh0kuQMMesuAawrfMxw14jrLzyoPLrjHyHMhymnhyD2beVxY64LltoF6pdISG1k5RDnMjCN881smfyF/f4yRl5hgLox09d0oeEu8ZOxRqz7AFDWBSdtsE7bJZEQUTLWtR1p9OWpu4WfRaC6yppmRufyJPlpAbs+wiMIXx2dXbOWc1IzveFqjBNj3B19qEpRoHBLHkwq87hpNxVM=
  on:
    tags: true
    repo: Dih5/comod
    python: 3.8
